# Generated by Django 2.1.5 on 2019-01-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedores',
            name='cel',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='tel',
        ),
    ]
