# Generated by Django 2.1.5 on 2019-01-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0002_auto_20190126_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='cel',
            field=models.IntegerField(default='00000'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fax',
            field=models.IntegerField(default='00000'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='tel',
            field=models.IntegerField(default='00000'),
        ),
    ]
