# Generated by Django 2.1.5 on 2019-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField()),
                ('qtde', models.IntegerField()),
                ('peso_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_liq', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_bruto_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_liq_total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('booking', models.CharField(max_length=50)),
                ('valor_usa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usa_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soma_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_embarque', models.IntegerField()),
                ('obs', models.TextField()),
            ],
        ),
    ]
