# Generated by Django 2.1.5 on 2019-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComInv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='CI_ident',
            field=models.CharField(default='nada', max_length=20),
        ),
    ]
