# Generated by Django 2.1.5 on 2019-01-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fornecedores', '0003_auto_20190126_2022'),
        ('Pacotes', '0001_initial'),
        ('Clientes', '0001_initial'),
        ('Portos', '0001_initial'),
        ('Materiais', '0001_initial'),
        ('ComInv', '0002_commercialinvoice_ci_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='ci_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.Clientes'),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='ci_fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fornecedores.Fornecedores'),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='ci_material',
            field=models.ManyToManyField(to='Materiais.Materiais'),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='ci_pacote',
            field=models.ManyToManyField(to='Pacotes.Pacotes'),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='ci_porto',
            field=models.ManyToManyField(to='Portos.Portos'),
        ),
    ]
