# Generated by Django 2.1.5 on 2019-01-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComInv', '0003_auto_20190127_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='ci_material',
        ),
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='ci_pacote',
        ),
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='peso_liq',
        ),
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='peso_unit',
        ),
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='qtde',
        ),
    ]
