# Generated by Django 2.1.5 on 2019-01-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComInv', '0005_commercialinvoice_ci_insercao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='valor_usa',
        ),
    ]
