# Generated by Django 2.1.5 on 2019-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComInv', '0006_remove_commercialinvoice_valor_usa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialinvoice',
            name='ci_insercao',
            field=models.ManyToManyField(blank=True, null=True, to='Insercoes.Insercao'),
        ),
        migrations.AlterField(
            model_name='commercialinvoice',
            name='ci_porto',
            field=models.ManyToManyField(blank=True, null=True, to='Portos.Portos'),
        ),
    ]
