# Generated by Django 2.1.5 on 2019-01-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComInv', '0008_auto_20190127_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialinvoice',
            name='ci_insercao',
        ),
    ]
