# Generated by Django 2.1.5 on 2019-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('rua', models.CharField(blank=True, max_length=150, null=True)),
                ('num', models.IntegerField()),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('pais', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.IntegerField()),
                ('cnpj', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('cel', models.IntegerField()),
                ('contato', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
