# Generated by Django 2.1.5 on 2019-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NCM', models.IntegerField()),
                ('material', models.CharField(max_length=50)),
            ],
        ),
    ]
