# Generated by Django 2.1.5 on 2019-01-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_balanca', models.CharField(max_length=50)),
                ('produto', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('motorista', models.CharField(max_length=50)),
                ('qtde_bags', models.IntegerField()),
                ('num_bags', models.IntegerField()),
                ('data', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('peso_veiculo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
